title: lijiawei's Homepage
page-top-title: Jiawei Li
top-section-bg-text: Earthquake Seismology
home-subtitle: Jiawei Li&ensp;|&ensp;李佳威
copyright-text: '&copy; Jiawei Li 2023-2024. All Rights Reserved.'
