title: Jiawei Li's Homepage
page-top-title: HOME
top-section-bg-text: Earthquake Seismology｜地震学
home-subtitle: Jiawei Li&ensp;|&ensp;李佳威
copyright-text: '&copy; Dr. Jiawei Li 2025. All Rights Reserved.'
